- apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: '2018-05-28T14:00:25Z'
      generation: 3
      labels:
        app: polaris-PRE
        template: polaris-springboot-pre
      name: pretest-dc
      namespace: pre
    spec:
      replicas: 2
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: pretest-dc
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: polaris-PRE
            deploymentconfig: pretest-dc
        spec:
          containers:
            - env:
                - name: JAVA_APP_JAR
                  value: spring-boot.jar
              name: deployment-pre
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            containerNames:
              - deployment-pre
            from:
              kind: ImageStreamTag
              name: 'polaris:latest'
              namespace: dev
          type: ImageChange
        - type: ConfigChange
