apiVersion: v1
kind: Template
labels:
  template: polaris-springboot-pre
message: This Template create all the polaris resources to deploy automatically a springboot jar in pre environment
metadata:
  annotations:
    description: This it deploy springboot application in pre environment
    iconClass: icon-jboss
    tags: polaris,springboot,pre
  name: polaris-PRE
parameters:
- displayName: MyProject project name
  value: pre
  name: PROJECT
  required: true
- displayName: environment dev
  value: dev
  name: ENVDEV
  required: true  
- displayName: Polaris application name
  value: polaris
  name: APP
  required: true    
- displayName: Name jar to Application Spring Boot
  value: spring-boot.jar
  name: JARNAME
  required: true
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP}-dc
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${APP}-dc
    template:
      metadata:
        labels:
          deploymentconfig: ${APP}-dc
      spec:
      
        containers:
         - env:
            - name: JAVA_APP_JAR
              value: ${JARNAME}
           image: ${ENVDEV}/${APP}:latest
           name: ${APP}
           ports:
             - containerPort: 8080
               protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30       
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}
        from:
          kind: ImageStreamTag
          name: ${APP}:latest
          namespace: ${ENVDEV}
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP}-r
  spec:
    to:
      kind: Service
      name: ${APP}-service